"""MicroMixPy config file support.

Config is stored in TOML format at ~/.micromixpy.toml by default.
Any value in the config can be overridden by an explicit CLI argument.

Precedence (highest → lowest):
  1. Explicit CLI argument
  2. Config file value
  3. Built-in default

Usage
-----
  micromixpy config --init     # write template to ~/.micromixpy.toml
  micromixpy config --show     # print effective config
  micromixpy --config /path/to/other.toml process ...
"""

from __future__ import annotations

import copy
import sys
import warnings
from pathlib import Path

if sys.version_info >= (3, 11):
    import tomllib
else:
    try:
        import tomllib
    except ImportError:
        import tomli as tomllib  # type: ignore[no-redef]

CONFIG_PATH: Path = Path.home() / ".micromixpy.toml"

# Built-in defaults — used when config key is absent
DEFAULT_CONFIG: dict = {
    "paths": {
        "mat_dir": "",
        "metadata": "",
        "output_dir": "",
    },
    "processing": {
        "dz_bin": 0.25,
        "dz_eps": 2.0,
        "nperseg": 512,
        "exclude_above": 0.0,
        "chi_method": "batchelor",
        "coherence_threshold": 0.5,
    },
    "gade": {
        "T_AW": None,
        "S_AW": None,
        "T_ice": -2.0,
    },
    "plots": {
        "ts_scalar": "turbidity_bin",
    },
}

_CONFIG_TEMPLATE = """\
# MicroMixPy configuration file
# Generated by: micromixpy config --init
# All values are optional — omit any key to use the built-in default.

[paths]
# Default directory containing .mat files.
# When set, "micromixpy process" accepts filenames without the full path.
mat_dir = ""

# Default path to the deployment metadata CSV.
metadata = ""

# Default output directory for processed netCDF files.
output_dir = ""

[processing]
# Bin size for binned CTD profiles (dbar ≈ m for shallow water).
dz_bin = 0.25

# Depth bin size for epsilon/chi computation (dbar).
dz_eps = 2.0

# Welch segment length in samples (512 = 1 s at 512 Hz).
nperseg = 512

# Exclude epsilon/chi bins at or above this pressure (dbar).
# Use to remove ship-hull-generated turbulence near the surface.
exclude_above = 0.0

# Method for chi estimation: "batchelor" (default) or "direct".
chi_method = "batchelor"

# Inter-thermistor coherence threshold for chi quality flag (0–1).
coherence_threshold = 0.5

[gade]
# Gade (1979) glacial meltwater mixing line parameters.
# T_AW and S_AW default to the warmest/saltiest point in each profile.
# T_ice is the glacier ice temperature (°C).
# T_AW =        # uncomment and set if known, e.g. T_AW = 2.5
# S_AW =        # e.g. S_AW = 34.5
T_ice = -2.0

[plots]
# Variable used to colour the T-S scatter diagnostic plot.
ts_scalar = "turbidity_bin"
"""


def load_config(path: Path = CONFIG_PATH) -> dict:
    """Load config from a TOML file, merging with DEFAULT_CONFIG.

    Missing keys fall back to DEFAULT_CONFIG values.
    Returns DEFAULT_CONFIG if the file is absent or invalid.
    """
    cfg = copy.deepcopy(DEFAULT_CONFIG)
    if not path.exists():
        return cfg
    try:
        with open(path, "rb") as fh:
            user = tomllib.load(fh)
        for section, values in user.items():
            if section in cfg and isinstance(values, dict):
                cfg[section].update(values)
            else:
                cfg[section] = values
    except Exception as exc:
        warnings.warn(f"Could not parse config {path}: {exc}. Using defaults.")
    return cfg


def write_template(path: Path = CONFIG_PATH, force: bool = False) -> None:
    """Write the config template to *path*.

    Raises FileExistsError if the file already exists and force=False.
    """
    if path.exists() and not force:
        raise FileExistsError(
            f"{path} already exists. Use --force to overwrite."
        )
    path.write_text(_CONFIG_TEMPLATE)


def show_config(cfg: dict) -> str:
    """Return a human-readable summary of the effective config."""
    lines = ["Effective MicroMixPy configuration:", ""]
    for section, values in cfg.items():
        lines.append(f"[{section}]")
        for key, val in values.items():
            lines.append(f"  {key} = {val!r}")
        lines.append("")
    return "\n".join(lines)
